
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: olares-instrumentation
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  exporter:
    endpoint: https://jaeger-storage-instance-collector.os-system:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://jaeger-storage-instance-collector.os-system:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
  dotnet:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://jaeger-storage-instance-collector.os-system:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
  nodejs:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://jaeger-storage-instance-collector.os-system:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
  nginx:
    image: bytetrade/autoinstrumentation-apache-httpd:1.0.4
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: https://jaeger-storage-instance-collector.os-system:4317
  go:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://jaeger-storage-instance-collector.os-system:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
    resource:
      limits:
        memory: 256Mi

---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: olares-instrumentation
  namespace: user-system-{{ .Values.bfl.username }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "before-hook-creation"

spec:
  exporter:
    endpoint: https://jaeger-storage-instance-collector.os-system:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://jaeger-storage-instance-collector.os-system:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
  dotnet:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://jaeger-storage-instance-collector.os-system:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
  nodejs:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://jaeger-storage-instance-collector.os-system:4318        
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
  nginx:
    image: bytetrade/autoinstrumentation-apache-httpd:1.0.4
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: https://jaeger-storage-instance-collector.os-system:4317
  go:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://jaeger-storage-instance-collector.os-system:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
    resource:
      limits:
        memory: 256Mi

