{{- $namespace := printf "%s" "os-system" -}}
{{- $rss_secret := (lookup "v1" "Secret" $namespace "rss-secrets") -}}
{{- $password := "" -}}
{{ if $rss_secret -}}
{{ $password = (index $rss_secret "data" "pg_password") }}
{{ else -}}
{{ $password = randAlphaNum 16 | b64enc }}
{{- end -}}

{{- $redis_password := "" -}}
{{ if $rss_secret -}}
{{ $redis_password = (index $rss_secret "data" "redis_password") }}
{{ else -}}
{{ $redis_password = randAlphaNum 16 | b64enc }}
{{- end -}}


{{- $redis_password_data := "" -}}
{{ $redis_password_data = $redis_password | b64dec }}

{{- $pg_password_data := "" -}}
{{ $pg_password_data = $password | b64dec }}

{{- $pg_user :=  printf "%s" "argo_os_system" -}}
{{- $pg_user = $pg_user | b64enc -}}

---

apiVersion: v1
kind: Secret
metadata:
  name: rss-secrets
  namespace: os-system
type: Opaque
data:
  pg_user: {{ $pg_user }}
  pg_password: {{ $password }}
  redis_password: {{ $redis_password }}

---
apiVersion: apr.bytetrade.io/v1alpha1
kind: MiddlewareRequest
metadata:
  name: rss-pg
  namespace: os-system
spec:
  app: rss
  appNamespace: os-system
  middleware: postgres
  postgreSQL:
    user: argo_os_system
    password: 
      valueFrom:
        secretKeyRef:
          key: pg_password
          name: rss-secrets
    databases:
    - name: rss
    - name: rss_v1
    - name: argo

---
apiVersion: apr.bytetrade.io/v1alpha1
kind: MiddlewareRequest
metadata:
  name: knowledge-redis
  namespace: os-system
spec:
  app: rss
  appNamespace: os-system
  middleware: redis
  redis:
    password:
      valueFrom:
        secretKeyRef:
          key: redis_password
          name: rss-secrets
    namespace: knowledge

---
    
apiVersion: v1
kind: Service
metadata:
  name: workflow-archivelog-s3
  namespace: os-system
spec:
  type: ClusterIP
  selector:
    app: systemserver
  ports:
    - protocol: TCP
      name: fakes3
      port: 4568
      targetPort: 4568
