{{- $namespace := printf "%s" "os-system" -}}
{{- $lldap_secret := (lookup "v1" "Secret" $namespace "lldap-credentials") -}}
{{- $lldap_jwt_secret := "" -}}
{{- $lldap_ldap_user_pass := "" -}}
{{- $lldap_key_seed := "" -}}
{{ if $lldap_secret -}}
{{ $lldap_jwt_secret = (index $lldap_secret "data" "lldap-jwt-secret") }}
{{ $lldap_ldap_user_pass = (index $lldap_secret "data" "lldap-ldap-user-pass") }}
{{ $lldap_key_seed = (index $lldap_secret "data" "lldap-key-seed") }}
{{ else -}}
{{ $lldap_jwt_secret = randAlpha 64 | b64enc }}
{{ $lldap_ldap_user_pass = randAlpha 64 | b64enc }}
{{ $lldap_key_seed = randAlpha 64 | b64enc }}
{{- end -}}

{{- $lldap_pg_secret := (lookup "v1" "Secret" $namespace "lldap-pg-secrets") -}}
{{- $pg_password := "" -}}
{{ if $lldap_pg_secret -}}
{{ $pg_password = (index $lldap_pg_secret "data" "pg_password") }}
{{ else -}}
{{ $pg_password = randAlphaNum 16 | b64enc }}
{{- end -}}

{{- $nats_password := "" -}}
{{ if $lldap_pg_secret -}}
{{ $nats_password = (index $lldap_pg_secret "data" "nats_password") }}
{{ else -}}
{{ $nats_password = randAlphaNum 16 | b64enc }}
{{- end -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: lldap-pg-secrets
  namespace: os-system
type: Opaque
data:
  pg_password: {{ $pg_password }}
  nats_password: {{ $nats_password }}

---
apiVersion: apr.bytetrade.io/v1alpha1
kind: MiddlewareRequest
metadata:
  name: lldap-pg
  namespace: os-system
spec:
  app: lldap
  appNamespace: os-system
  middleware: postgres
  postgreSQL:
    user: lldap_os_system
    password:
      valueFrom:
        secretKeyRef:
          key: pg_password
          name: lldap-pg-secrets
    databases:
      - name: lldap

---
apiVersion: apr.bytetrade.io/v1alpha1
kind: MiddlewareRequest
metadata:
  name: lldap-nats
  namespace: {{ .Release.Namespace }}
spec:
  app: lldap
  appNamespace: {{ .Release.Namespace }}
  middleware: nats
  nats:
    password:
      valueFrom:
        secretKeyRef:
          key: nats_password
          name: lldap-pg-secrets
    refs:
    - appName: notifications
      appNamespace: {{ .Release.Namespace }}
      subjects:
      - name: system.notification
        perm:
        - pub
        - sub
    user: os-system-lldap

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    lldap: https://github.com/nitnelave/lldap
    k8s: https://github.com/Evantage-WS/lldap-kubernetes
  labels:
    app: lldap
    applications.app.bytetrade.io/author: bytetrade.io
  name: lldap
  namespace: os-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lldap
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        lldap: https://github.com/nitnelave/lldap
        k8s: https://github.com/Evantage-WS/lldap-kubernetes
      labels:
        app: lldap
    spec:
      containers:
        - env:
            - name: GID
              value: "1001"
            - name: LLDAP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lldap-credentials
                  key: lldap-jwt-secret
            - name: LLDAP_LDAP_BASE_DN
              valueFrom:
                secretKeyRef:
                  name: lldap-credentials
                  key: base-dn
            - name: LLDAP_LDAP_USER_DN
              valueFrom:
                secretKeyRef:
                  name: lldap-credentials
                  key: lldap-ldap-user-dn
            - name: LLDAP_LDAP_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: lldap-credentials
                  key: lldap-ldap-user-pass
            - name: LLDAP_KEY_SEED
              valueFrom:
                secretKeyRef:
                  name: lldap-credentials
                  key: lldap-key-seed
            - name: TZ
              value: CET
            - name: UID
              value: "1001"
            - name: LLDAP_KEY_FILE
              value: "/data/private_key"
            - name: RUST_BACKTRACE
              value: "full"
            - name: LLDAP_DATABASE_URL
              value: "postgres://lldap_os_system:{{ $pg_password | b64dec }}@citus-0.citus-headless.os-system:5432/os_system_lldap?sslmode=allow"
            - name: NATS_HOST
              value: nats
            - name: NATS_PORT
              value: "4222"
            - name: NATS_USERNAME
              value: os-system-lldap
            - name: NATS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: nats_password
                  name: lldap-pg-secrets
            - name: NATS_SUBJECT
              value: "terminus.{{ .Release.Namespace }}.system.notification"

          image: beclab/lldap:0.0.1
          imagePullPolicy: IfNotPresent
          name: lldap
          ports:
            - containerPort: 3890
            - containerPort: 17170


---
apiVersion: v1
kind: Service
metadata:
  annotations:
    lldap: https://github.com/nitnelave/lldap
    k8s: https://github.com/Evantage-WS/lldap-kubernetes
  labels:
    app: lldap-service
  name: lldap-service
  namespace: os-system
spec:
  ports:
    - name: "3890"
      port: 3890
      targetPort: 3890
    - name: "17170"
      port: 17170
      targetPort: 17170
  selector:
    app: lldap
---
apiVersion: v1
data:
  base-dn: ZGM9ZXhhbXBsZSxkYz1jb20=
  lldap-jwt-secret: {{ $lldap_jwt_secret }}
  lldap-ldap-user-dn: YWRtaW4=
  lldap-ldap-user-pass: {{ $lldap_ldap_user_pass }}
  lldap-key-seed: {{ $lldap_key_seed }}
kind: Secret
metadata:
  name: lldap-credentials
  namespace: os-system
type: Opaque
