---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizard
  namespace: {{ .Release.Namespace }}
  labels:
    app: wizard
    applications.app.bytetrade.io/author: bytetrade.io
  annotations:
    applications.app.bytetrade.io/version: '0.0.1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wizard
  template:
    metadata:
      labels:
        app: wizard
    spec:
      initContainers:
      - args:
        - -it
        - authelia-backend.os-framework:9091
        image: owncloudci/wait-for:latest
        imagePullPolicy: IfNotPresent
        name: check-auth

      containers:
      - name: wizard
        image: beclab/wizard:v1.4.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: apiServerURL
            value: http://bfl.{{ .Release.Namespace }}:8080
      volumes:
      - name: userspace-dir
        hostPath:
          type: Directory
          path: "{{ .Values.userspace.userData }}"

---
apiVersion: v1
kind: Service
metadata:
  name: wizard
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: wizard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      {{ if and .Values.desktop .Values.desktop.nodeport }}
      nodePort: {{ .Values.desktop.nodeport }}
      {{ end }}

